### ISSUE TITLE
Is the zipkin-dependency topic mandatory?

### ISSUE THREAD

**Issue by drolando** [sysco-middleware/zipkin-dependencies-streaming#7]
From the README it seems this code will always emit the dependencies to another Kafka topic. And then optionally to ES or Cassandra.

Is there a way to avoid this temporary topic?

**Comment by jeqo** [comment]
This topic was created as a changelog and potentially to store deps when downstream storage is not available or we want many destinations. 

Anyhow, i agree that making this optional could be useful as well to avoid mantaining multiple topics.

**Comment by jeqo** [comment]
@drolando, in a second thought, internal topics are already supporting the dependency-link changelog. I have applied changes, and `zipkin-dependency` topics is not required anymore. 

Looking forward to your feedback :)
